### PR TITLE
Fix SparkWebContext getFullRequestURL to include the client queryString

### PR DESCRIPTION
**Pull request by greven**
Here it is the fix for the issue discussed here: https://github.com/pac4j/spark-pac4j/issues/4.
I will be able to test with my project.
Thanks!

### CODE REVIEW

**Comment by greven** [comment]
Travis failed but it seems to be a deployment permission error?

**Comment by leleuj** [comment]
Yes, the build fails because of the Sonatype deployment, which should never happen for a PR -> tracking the issue: https://github.com/pac4j/spark-pac4j/issues/6

Thanks for your patience and tenacity. I'll re-test everything and release a new 1.0.3.

I'm currently working on the new implem for J2E and Play (based on pac4j v1.8): REST support (LDAP, DB, Mongo, JWT authentication mechanisms) + authorizations, but if I see some interest in spark-pac4j, I may update it just after that.

**Comment by greven** [comment]
Thanks for the merge and patience too!
I'll wait for the release to test everything and will update you on that.

Best regards.

**Comment by leleuj** [comment]
Indeed, there is a problem with pac4j-saml version 1.7.1, I saved the current master demo in the 1.7.1 branch and revert the master to use pac4j v1.7.0 and open an issue: https://github.com/pac4j/pac4j/issues/219 to fix that in pac4j v1.8.

I re-uploaded the metadata to make the SAML authentication work and verify that your PR fixes this issue.

I just released spark-pac4j v1.0.3, it should be available in the Maven central repository in a few hours.

I'll do more tests for the version 1.1 (based on pac4j v1.8).

**Comment by leleuj** [comment]
Just sent a message on the mailing list to announce the new release.

**Pull request merged**
